let mimes = {
  txt: 'text/plain',
  log: 'text/plain',
  // log: 'application/octet-stream',
  htm: 'text/html',
  html: 'text/html',
  xml: 'text/xml',
  text: 'text/plain',
  css: 'text/css',
  less: 'text/css',
  js: 'text/javascript',

  gif: 'image/gif',
  jpg: 'image/jpeg',
  png: 'image/png',
  bmp: 'image/bmp',
  ico: 'image/x-icon',
  jpeg: 'image/jpeg',
  tiff: 'image/tiff',
  ico: 'image/x-icon',
  svg: 'image/svg+xml',

  avi: 'video/avi',
  mp4: 'video/mp4',
  wav: 'audio/x-wav',
  wmv: 'video/x-ms-wmv',
  wma: 'audio/x-ms-wma',

  mp3: 'audio/mpeg',
  wav: 'audio/wav',
  wmv: 'video/x-ms-wmv',

  pdf: 'application/pdf',
  chm: 'application/octet-stream',
  mdb: 'application/msaccess',
  sql: 'application/octet-stream',
  con: 'application/octet-stream',
  dat: 'application/octet-stream',
  ini: 'application/octet-stream',
  php: 'application/octet-stream',
  ttf: 'application/octet-stream',
  fon: 'application/octet-stream',
  js: 'application/x-javascript',
  dll: 'application/octet-stream',
  xls: 'application/vnd.ms-excel',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ppt: 'application/vnd.ms-powerpoint',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  zip: 'application/x-zip-compressed',
  rar: 'application/x-zip-compressed',
  psd: 'application/octet-stream',
  '7z': 'application/octet-stream',
  exe: 'application/octet-stream',
  rmvb: 'application/vnd.rn-realmedia-vbr',
  '3gp': 'application/octet-stream',
  flv: 'application/octet-stream',
  krc: 'application/octet-stream',
  lrc: 'application/octet-stream',
  json: 'application/json',
  swf: 'application/x-shockwave-flash',
  xsxl: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
}

module.exports = mimes
